env: cn
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_demo?useSSL=false&serverTimezone=CTT
    username: root
    password: root
  redis:
      #数据库索引
      database: 0
      host: 192.168.8.106
      port: 6380
      password: 12345678
      #连接超时时间
      timeout: 10000
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
servlet:
  tomcat:
    uri-encoding: utf-8
debug: true
server:
  port: 8888
  servlet.context-path: /jwt-demo
mybatis:
  type-aliases-package: com.test.modle
  mapper-locations: classpath:/sqlMapper/*
  configuration:
    mapUnderscoreToCamelCase: true
springfox.documentation.swagger.v2.path: /api-docs



